runserver:
	poetry run python src/manage.py runserver

makemigrations:
	poetry run python src/manage.py makemigrations

migrate:
	poetry run python src/manage.py migrate

flake8:
	poetry run flake8 --config  .flake8